# WEB SCRAPING ASSIGNMENT - 1

# Q.1 Write a python program to display all the header tags from wikipedia.org and make data frame.

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page=requests.get('https://en.wikipedia.org/wiki/Main_Page')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
header_tags = []

In [1620]:
for i in soup.find_all('span',class_="mw-headline"):
    header_tags.append(i.text)
header_tags

['Welcome to Wikipedia',
 "From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages']

# Q2. Write a python program to display IMDB’s Top rated 50 movies’ data (i.e. name, rating, year of release) and make data frame.

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page=requests.get('https://www.imdb.com/list/ls055386972/?sort=user_rating,desc&st_dt=&mode=detail&page=1')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
movie_name=soup.find('h3',class_="lister-item-header")
movie_name.text.split('\n')[2]

In [ ]:
movie_names=[]

In [ ]:
for i in soup.find_all('h3',class_="lister-item-header"):
    movie_names.append(i.text.split('\n')[2])
movie_names

In [ ]:
print(len(movie_names))

In [ ]:
movie_year = []

In [ ]:
for i in soup.find_all('span',class_="lister-item-year"):
    movie_year.append(i.text)

In [ ]:
movie_year

In [ ]:
print(len(movie_year))

In [ ]:
movie_rating=soup.find('div',class_="ipl-rating-star small")
movie_rating.text.split('\n')[1]

In [ ]:
IMDB_ratings = []

In [ ]:
for i in soup.find_all('div',class_="ipl-rating-star small"):
    IMDB_ratings.append(i.text.split('\n')[8])

In [ ]:
IMDB_ratings

In [1621]:
import pandas as pd
df = pd.DataFrame({'Movie Name':movie_names,'Year of Release':movie_year,'Movie Rating':IMDB_ratings})
df

                                    Movie Name Year of Release Movie Rating
0                     The Shawshank Redemption          (1994)          9.3
1                                The Godfather          (1972)          9.2
2                              The Dark Knight          (2008)            9
3                             Schindler's List          (1993)            9
4                                 12 Angry Men          (1957)            9
5              Il buono, il brutto, il cattivo          (1966)          8.8
6                               The Green Mile          (1999)          8.6
7                   Terminator 2: Judgment Day          (1991)          8.6
8                          Saving Private Ryan          (1998)          8.6
9                              La vita è bella          (1997)          8.6
10                       It's a Wonderful Life          (1946)          8.6
11                               Seven Samurai          (1954)          8.6
12                                   Gladiator          (2000)          8.5
13                          Back to the Future          (1985)          8.5
14                                       Alien          (1979)          8.5
15                                        Léon          (1994)          8.5
16                                 The Pianist          (2002)          8.5
17                                Intouchables          (2011)          8.5
18                                 The Shining          (1980)          8.4
19                                  Braveheart          (1995)          8.4
20                         Requiem for a Dream          (2000)          8.3
21                     Jodaeiye Nader az Simin          (2011)          8.3
22                               Jurassic Park          (1993)          8.2
23                             The Sixth Sense          (1999)          8.2
24                           Kill Bill: Vol. 1          (2003)          8.2
25                            A Beautiful Mind          (2001)          8.2
26                                Finding Nemo          (2003)          8.2
27                      El secreto de sus ojos          (2009)          8.2
28                The Bridge on the River Kwai          (1957)          8.2
29                           Bacheha-Ye aseman          (1997)          8.2
30                                The Exorcist          (1973)          8.1
31                              Salinui chueok          (2003)          8.1
32                                 Gran Torino          (2008)          8.1
33                                     Ben-Hur          (1959)          8.1
34                         Hachi: A Dog's Tale          (2009)          8.1
35                               Amores perros          (2000)          8.1
36                        A Moment to Remember          (2004)          8.1
37                    The Pursuit of Happyness          (2006)            8
38                        Yeopgijeogin geunyeo          (2001)            8
39  Spring, Summer, Fall, Winter... and Spring          (2003)            8
40                                   Okuribito          (2008)            8
41                           Central do Brasil          (1998)            8
42                                     Titanic          (1997)          7.9
43                                      3-Iron          (2004)          7.9
44                              Vozvrashchenie          (2003)          7.9
45                                  Apocalypto          (2006)          7.8
46                                   Cast Away          (2000)          7.8
47                                       Taken      (I) (2008)          7.8
48                             I Saw the Devil          (2010)          7.8
49                               The Road Home          (1999)          7.8

#        3. Write a python program to display IMDB’s Top rated 50 Indian movies’ data (i.e. name, rating, year of release) and make data frame.

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page=requests.get('https://www.imdb.com/list/ls025646548/')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
bollywood_movie_name=soup.find('h3',class_="lister-item-header")
bollywood_movie_name.text.split('\n')[2]

In [ ]:
bollywood_movie_names = []

In [ ]:
for i in soup.find_all('h3',class_="lister-item-header"):
    bollywood_movie_names.append(i.text.split('\n')[2])
bollywood_movie_names

In [ ]:
print(len(bollywood_movie_names))

In [ ]:
bollywood_movie_year = []

In [ ]:
for i in soup.find_all('span',class_="lister-item-year"):
    bollywood_movie_year.append(i.text)

In [ ]:
bollywood_movie_year

In [ ]:
print(len(bollywood_movie_year))

In [ ]:
bollywood_movie_rating=soup.find('div',class_="ipl-rating-star small")
bollywood_movie_rating.text.split('\n')[8]

In [ ]:
IMDB_bollywood_ratings = []

In [ ]:
for i in soup.find_all('div',class_="ipl-rating-star small"):
    IMDB_bollywood_ratings.append(i.text.split('\n')[8])


IMDB_bollywood_ratings

In [1622]:
import pandas as pd
df = pd.DataFrame({'Movie Name':bollywood_movie_names,'Year of Release':bollywood_movie_year, 'Movie Rating':IMDB_bollywood_ratings})
df

                           Movie Name Year of Release Movie Rating
0                              Awaara          (1951)          7.8
1                           Shree 420          (1955)          7.9
2                              Pyaasa          (1957)          8.3
3                           Madhumati          (1958)          7.8
4                              Kanoon          (1960)          7.9
5                       Mughal-E-Azam          (1960)          8.1
6                          Kala Bazar          (1960)          7.1
7                       Woh Kaun Thi?          (1964)          7.5
8                               Guide          (1965)          8.4
9                            Amrapali          (1966)          6.7
10                              Anand          (1971)          8.1
11                        Rajnigandha          (1974)          7.3
12      Arvind Desai Ki Ajeeb Dastaan          (1978)          7.2
13                     Satte Pe Satta          (1982)          7.2
14                       Disco Dancer          (1982)          6.4
15                 Jaane Bhi Do Yaaro          (1983)          8.3
16                         Ardh Satya          (1983)          8.1
17                              Katha          (1983)          7.7
18                            Parinda          (1989)          7.8
19                           Baazigar          (1993)          7.6
20                               Darr          (1993)          7.6
21                           Rangeela          (1995)          7.4
22        Dilwale Dulhania Le Jayenge          (1995)            8
23                             Border      (I) (1997)          7.9
24                              Satya          (1998)          8.3
25                              Kaun?          (1999)          7.8
26                         Hera Pheri          (2000)          8.1
27  Lagaan: Once Upon a Time in India          (2001)          8.1
28                            Company          (2002)            8
29                     Darna Mana Hai          (2003)          6.3
30                Munna Bhai M.B.B.S.          (2003)          8.1
31                             Khakee          (2004)          7.4
32                         Veer-Zaara          (2004)          7.8
33             Swades: We, the People          (2004)          8.2
34       Main, Meri Patni... Aur Woh!          (2005)          7.2
35                       Garam Masala          (2005)          6.7
36                                دون      (I) (2006)          7.1
37                               Guru          (2007)          7.7
38                     Chak De! India          (2007)          8.1
39                         No Smoking          (2007)          7.3
40                        A Wednesday          (2008)          8.1
41                           3 Idiots          (2009)          8.4
42                    My Name Is Khan          (2010)          7.9
43                          Guzaarish          (2010)          7.4
44           Zindagi Na Milegi Dobara          (2011)          8.2
45                           Rockstar          (2011)          7.7
46                              Don 2          (2011)            7
47                               Piku          (2015)          7.6
48                            Airlift          (2016)          7.9
49                       اللحن الأعمى          (2018)          8.2

# 4. Write s python program to display list of respected former presidents of India(i.e. Name , Term of office)
from https://presidentofindia.nic.in/former-presidents.htm and make data frame.

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page = requests.get('https://presidentofindia.nic.in/former-presidents.htm')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
president_name=soup.find('div',class_="presidentListing")
president_name.text.split('\n')[1]

In [ ]:
president_names = []

In [ ]:
for i in soup.find_all('div',class_="presidentListing"):
    president_names.append(i.text.split('\n')[1])
president_names

In [ ]:
print(len(president_names))

In [ ]:
president_term=soup.find('div',class_="presidentListing")
president_term.text.split('Term of Office:')[1]

In [ ]:
president_terms = []

In [ ]:
for i in soup.find_all('div',class_="presidentListing"):
    president_terms.append(i.text.split('Term of Office:')[1])
president_terms

In [ ]:
print(len(president_terms))

In [1623]:
import pandas as pd
df = pd.DataFrame({'President Name':president_names,'Term':president_terms})
df

,President Name,Term
0,Shri Ram Nath Kovind (birth - 1945),"25 July, 2017 to 25 July, 2022 \nhttps://ramn..."
1,Shri Pranab Mukherjee (1935-2020),"25 July, 2012 to 25 July, 2017 \nhttp://prana..."
2,Smt Pratibha Devisingh Patil (birth - 1934),"25 July, 2007 to 25 July, 2012 \nhttp://prati..."
3,DR. A.P.J. Abdul Kalam (1931-2015),"25 July, 2002 to 25 July, 2007 \nhttp://abdul..."
4,Shri K. R. Narayanan (1920 - 2005),"25 July, 1997 to 25 July, 2002 \n"
5,Dr Shankar Dayal Sharma (1918-1999),"25 July, 1992 to 25 July, 1997 \n"
6,Shri R Venkataraman (1910-2009),"25 July, 1987 to 25 July, 1992 \n"
7,Giani Zail Singh (1916-1994),"25 July, 1982 to 25 July, 1987 \n"
8,Shri Neelam Sanjiva Reddy (1913-1996),"25 July, 1977 to 25 July, 1982 \n"
9,Dr. Fakhruddin Ali Ahmed (1905-1977),"24 August, 1974 to 11 February, 1977\n"
10,Shri Varahagiri Venkata Giri (1894-1980),"3 May, 1969 to 20 July, 1969 and 24 August, 1..."
11,Dr. Zakir Husain (1897-1969),"13 May, 1967 to 3 May, 1969\n"
12,Dr. Sarvepalli Radhakrishnan (1888-1975),"13 May, 1962 to 13 May, 1967\n"
13,Dr. Rajendra Prasad (1884-1963),"26 January, 1950 to 13 May, 1962\n"

#    5.Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape and make data frame-
a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
b) Top 10 ODI Batsmen along with the records of their team andrating.
c) Top 10 ODI bowlers along with the records of their team andrating.

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page = requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
oditeam_ranking = []

In [ ]:
for i in soup.find_all('span',class_="u-hide-phablet"):
    oditeam_ranking.append(i.text)
oditeam_ranking

# Q.9 Write a python program to scrape mentioned details from dineout.co.in and make data frame-
i) Restaurant name
ii) Cuisine
iii) Location
iv) Ratings
v) Image URL

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page = requests.get('https://www.dineout.co.in/delhi-restaurants/buffet-special')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
restruant_name = []

In [ ]:
for i in soup.find_all('a',class_="restnt-name ellipsis"):
    restruant_name.append(i.text)
restruant_name

In [ ]:
restruant_location = []

In [ ]:
for i in soup.find_all('div',class_="restnt-loc ellipsis"):
    restruant_location.append(i.text)
restruant_location

In [ ]:
restruant_images = []

In [ ]:
for i in soup.find_all('img',class_="no-img"):
    restruant_images.append(i.get('data-src'))
restruant_images

In [ ]:
rest_rating = []

In [ ]:
for i in soup.find_all('div',class_="restnt-rating rating-4"):
    rest_rating.append(i.text)
rest_rating

In [ ]:
rest_cuisine = []

In [ ]:
for i in soup.find_all('span',class_="double-line-ellipsis"):
    rest_cuisine.append(i.text.split('|')[1])
rest_cuisine

In [1624]:
import pandas as pd
df=pd.DataFrame({'Restaurant Name':restruant_name,'Cuisines':rest_cuisine,'Location':restruant_location,'Ratings':rest_rating,'Image URL':restruant_images})
df

,Restaurant Name,Cuisines,Location,Ratings,Image URL
0,Castle Barbeque,"Chinese, North Indian","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
1,Jungle Jamboree,"North Indian, Asian, Italian","3CS Mall,Lajpat Nagar - 3, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
2,Cafe Knosh,"Italian, Continental","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
3,Castle Barbeque,"Chinese, North Indian","Pacific Mall,Tagore Garden, West Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
4,The Barbeque Company,"North Indian, Chinese","Gardens Galleria,Sector 38A, Noida",3.9,https://im1.dineout.co.in/images/uploads/resta...
5,India Grill,"North Indian, Italian","Hilton Garden Inn,Saket, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
6,Delhi Barbeque,North Indian,"Taurus Sarovar Portico,Mahipalpur, South Delhi",3.6,https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que Village,North Indian,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.8,https://im1.dineout.co.in/images/uploads/resta...
8,Indian Grill Room,"North Indian, Mughlai","Suncity Business Tower,Golf Course Road, Gurgaon",4.3,https://im1.dineout.co.in/images/uploads/resta...

# Q.8 Write a python program to scrape the details of most downloaded articles from AI in last 90 days.https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles Scrape below mentioned details and make data frame-
i) Paper Title
ii) Authors
iii) Published Date
iv) Paper URL

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page = requests.get('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
title = []

In [ ]:
for i in soup.find_all('h2',class_="sc-1qrq3sd-1 gRGSUS sc-1nmom32-0 sc-1nmom32-1 btcbYu goSKRg"):
    title.append(i.text)
title

In [ ]:
authors = []

In [ ]:
for i in soup.find_all('span',class_="sc-1w3fpd7-0 dnCnAO"):
    authors.append(i.text)
authors

In [ ]:
published_date=[]

In [ ]:
for i in soup.find_all('span',class_="sc-1thf9ly-2 dvggWt"):
    published_date.append(i.text)
published_date

In [ ]:
paper_URL = []

In [ ]:
for i in soup.find_all('a',class_="sc-5smygv-0 fIXTHm"):
    paper_URL.append(i.get('href'))
paper_URL

In [1625]:
import pandas as pd
df = pd.DataFrame({'Paper Title':title,'Authors':authors,'Published Date':published_date,'Paper URL':paper_URL})
df

,Paper Title,Authors,Published Date,Paper URL
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021,https://www.sciencedirect.com/science/article/...
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021,https://www.sciencedirect.com/science/article/...
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015,https://www.sciencedirect.com/science/article/...
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998,https://www.sciencedirect.com/science/article/...
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017,https://www.sciencedirect.com/science/article/...
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019,https://www.sciencedirect.com/science/article/...
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021,https://www.sciencedirect.com/science/article/...
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015,https://www.sciencedirect.com/science/article/...
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999,https://www.sciencedirect.com/science/article/...
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020,https://www.sciencedirect.com/science/article/...
10,Evaluating XAI: A comparison of rule-based and...,"van der Waa, Jasper, Nieuwburg, Elisabeth, Cre...",February 2021,https://www.sciencedirect.com/science/article/...
11,Argumentation in artificial intelligence,"Bench-Capon, T.J.M., Dunne, Paul E.",October 2007,https://www.sciencedirect.com/science/article/...
12,Algorithms for computing strategies in two-pla...,"Bošanský, Branislav, Lisý, Viliam and 3 more",August 2016,https://www.sciencedirect.com/science/article/...
13,Multiple object tracking: A literature review,"Luo, Wenhan, Xing, Junliang and 4 more",April 2021,https://www.sciencedirect.com/science/article/...
14,Selection of relevant features and examples in...,"Blum, Avrim L., Langley, Pat",December 1997,https://www.sciencedirect.com/science/article/...
15,A survey of inverse reinforcement learning: Ch...,"Arora, Saurabh, Doshi, Prashant",August 2021,https://www.sciencedirect.com/science/article/...
16,Explaining individual predictions when feature...,"Aas, Kjersti, Jullum, Martin, Løland, Anders",September 2021,https://www.sciencedirect.com/science/article/...
17,A review of possible effects of cognitive bias...,"Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Joha...",June 2021,https://www.sciencedirect.com/science/article/...
18,Integrating social power into the decision-mak...,"Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.",December 2016,https://www.sciencedirect.com/science/article/...
19,“That's (not) the output I expected!” On the r...,"Riveiro, Maria, Thill, Serge",September 2021,https://www.sciencedirect.com/science/article/...
20,Explaining black-box classifiers using post-ho...,"Kenny, Eoin M., Ford, Courtney, Quinn, Molly, ...",May 2021,https://www.sciencedirect.com/science/article/...
21,Algorithm runtime prediction: Methods & evalua...,"Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyto...",January 2014,https://www.sciencedirect.com/science/article/...
22,Wrappers for feature subset selection,"Kohavi, Ron, John, George H.",December 1997,https://www.sciencedirect.com/science/article/...
23,Commonsense visual sensemaking for autonomous ...,"Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srik...",October 2021,https://www.sciencedirect.com/science/article/...
24,"Quantum computation, quantum theory and AI","Ying, Mingsheng",February 2010,https://www.sciencedirect.com/science/article/...

# Q.7 Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world and make data frame-
i) Headline ii) Time
iii) NewsLink

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
page = requests.get('https://www.cnbc.com/world/?region=world')

In [ ]:
page

In [ ]:
soup=BeautifulSoup(page.content)

In [ ]:
soup

In [ ]:
headline = []

In [ ]:
for i in soup.find_all('a',class_="LatestNews-headline"):
    headline.append(i.text)
headline

In [ ]:
time_cast = []

In [ ]:
for i in soup.find_all('time',class_="LatestNews-timestamp"):
    time_cast.append(i.text)
time_cast

In [ ]:
News_link = []

In [ ]:
for i in soup.find_all('a',class_="LatestNews-headline"):
    News_link.append(i.get('href'))
News_link

In [1626]:
import pandas as pd
importlib.reload(pd)
df=pd.DataFrame({'Headline':headline,'TIME':time_cast,'NEWS LINK':News_link})
df

,Headline,TIME,NEWS LINK
0,A 27-year-old raised over $1 million to build ...,22 Min Ago,https://www.cnbc.com/2023/02/26/how-entreprene...
1,"Portugal, Spain and 8 other countries where a ...",22 Min Ago,https://www.cnbc.com/2023/02/26/least-expensiv...
2,Barbara Corcoran: I made $1 million in a day s...,1 Hour Ago,https://www.cnbc.com/2023/02/26/how-barbara-co...
3,A-list designers are offering virtual help at ...,2 Hours Ago,https://www.cnbc.com/2023/02/26/post-pandemic-...
4,How the Creed franchise makes a statement – an...,3 Hours Ago,https://www.cnbc.com/2023/02/26/creed-iii-new-...
5,Cramer sees a 'good chance' Salesforce's Benio...,17 Hours Ago,https://www.cnbc.com/2023/02/25/cramer-sees-a-...
6,Warren Buffett’s equity portfolio is focused o...,"February 25, 2023",https://www.cnbc.com/2023/02/25/warren-buffett...
7,"3 tips for new runners, from a running coach a...","February 25, 2023",https://www.cnbc.com/2023/02/25/3-tips-for-new...
8,26-year-old pays $0 to live in a 'luxury tiny ...,"February 25, 2023",https://www.cnbc.com/2023/02/25/26-year-lives-...
9,Here are highlights from Warren Buffett's annu...,"February 25, 2023",https://www.cnbc.com/2023/02/25/highlights-fro...
10,Top 10 U.S. towns where millionaires are buyin...,"February 25, 2023",https://www.cnbc.com/2023/02/25/us-towns-milli...
11,How the 'Henderson test' could weaken Section ...,"February 25, 2023",https://www.cnbc.com/2023/02/25/internet-free-...
12,Buffett calls stock buyback critics 'economic ...,"February 25, 2023",https://www.cnbc.com/2023/02/25/warren-buffett...
13,Movie theaters aren't dying — they're evolving,"February 25, 2023",https://www.cnbc.com/2023/02/25/movie-theaters...
14,How representation of Black artists in galleri...,"February 25, 2023",https://www.cnbc.com/2023/02/25/how-representa...
15,Nokia launches smartphone you can fix yourself...,"February 25, 2023",https://www.cnbc.com/2023/02/25/hmd-global-lau...
16,"The 10 worst-paying college majors, five years...","February 25, 2023",https://www.cnbc.com/2023/02/25/worst-paying-c...
17,The mortgage rate you get depends partly on yo...,"February 25, 2023",https://www.cnbc.com/2023/02/25/mortgage-rate-...
18,"Berkshire operating earnings fall 8%, cash hoa...","February 25, 2023",https://www.cnbc.com/2023/02/25/berkshire-hath...
19,Read Warren Buffett’s annual letter to Berkshi...,"February 25, 2023",https://www.cnbc.com/2023/02/25/read-warren-bu...
20,Cramer says the six things needed for market s...,"February 24, 2023",https://www.cnbc.com/2023/02/24/jim-cramer-the...
21,"Pence, possible Trump 2024 challenger, slams '...","February 24, 2023",https://www.cnbc.com/2023/02/24/mike-pence-ex-...
22,Elon Musk's Twitter has been sued by at least ...,"February 24, 2023",https://www.cnbc.com/2023/02/24/musks-twitter-...
23,Warner Bros. Discovery sues Paramount over 'So...,"February 24, 2023",https://www.cnbc.com/2023/02/24/warner-bros-di...
24,"How TV dinners changed American cooking, forever","February 24, 2023",https://www.cnbc.com/2023/02/24/how-tv-dinners...
25,Inflation takes a back seat to earnings next w...,"February 24, 2023",https://www.cnbc.com/2023/02/24/inflation-seco...
26,Pro Picks: Watch all of Friday's big stock cal...,"February 24, 2023",https://www.cnbc.com/2023/02/24/pro-picks-watc...
27,Space Force is taking a 'mutual fund approach'...,"February 24, 2023",https://www.cnbc.com/2023/02/24/space-force-ro...
28,Here are the U.S. cities most vulnerable to cl...,"February 24, 2023",https://www.cnbc.com/2023/02/24/us-cities-most...
29,The Oscars are 2 weeks away—How to watch all 1...,"February 24, 2023",https://www.cnbc.com/2023/02/24/where-to-watch...